### ISSUE TITLE
two times preRelease

### ISSUE THREAD

**Issue by skoppe** [symmetryinvestments/dsemver#3]
https://github.com/symmetryinvestments/dsemver/blob/master/source/dsemver/semver.d#L69

**Comment by skoppe** [comment]
For both preRelease and buildIdentifier

**Comment by burner** [comment]
classic copy paste

**Comment by burner** [comment]
how did you find that one?

**Comment by skoppe** [comment]
I am using your library in SIL actually :) Just the semver parsing really.

Just glancing over the code, looking for whether it handled the string -> SemVer -> string conversion properly.

**Comment by burner** [comment]
cool, thanks
