### ISSUE TITLE
Support semver 0.y.z

### ISSUE THREAD

**Issue by chances** [symmetryinvestments/dsemver#5]
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

https://semver.org/#spec-item-4

---

In my use case I have an _unstable_ API, but I'd still like to share it on dub.

**Comment by burner** [comment]
dsemver != semver

I know where you are coming from but dsemver come for facing 0.y.z hell as the documentation stats.

> First release is 1.0.0. There is no 0.x.x nightmare.

Meaning. Release 1.0.0. If you break the api release 2.0.0 and continue. If you end up at verison 1337.0.0, so be it.
At least I know that there is a breaking change between 1336 and 1337. Better than being at 0.1337 that has no meaning.

Sorry for the rant, I'll try to make the documentation more clear about this fact.
Thank you for creating the issue.
